### ISSUE TITLE
Additional services

### ISSUE THREAD

**Issue by phantomnat** [bigbearsio/strength-ref#2]
I think it would be great if we made the rules a bit more real world.
1. After `book(round, seat)` was called, `confirm(seat)` must be call within `x` seconds (assume that, this call from the payment gateway, etc.) or else the seat will be available for another user.
2. If users don't satisfied with the reservation result, they can `cancel(round, seat)` it. Then another user can have that seat.

What do you think?

**Comment by varokas** [comment]
This is an awesome idea. How about we do it like this ? 

1. getRemaining() -> return up to 10 available seats
2. reserve(seat) -> reserve the seat for up to X seconds 
3. Confirm (seat) -> confirm booking 
4. Cancel (seat) -> cancel the rsvp 
 
All thesr api will return value for current round. The user wouldnt have control over what round they want 

Note that “rounds” are just somewhat artificial constructs to impose some resource contention while allowing the system to continue forever (never run out of tickets)

**Comment by varokas** [comment]
@mahasak @tspn  looks good to u ?

**Comment by tnuanchuay** [comment]
LGTM

**Comment by varokas** [comment]
PR? =D

**Comment by phantomnat** [comment]
Yeah, I'll give it a try.

**Comment by phantomnat** [comment]
I created a PR #3.
How about it?

**Comment by varokas** [comment]
closed as #3 is merged. Thanks for contributing
